import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader
from transformers import GPT2Tokenizer, GPT2LMHeadModel, GPT2Config

class EmployeeDataset(Dataset):
    def __init__(self, data, max_length):
        self.data = data
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        input_text = self.data[idx]['input_ids'][:self.max_length]
        target_text = self.data[idx]['target_ids'][:self.max_length]
        return input_text, target_text

# Prepare your dataset with employee IDs and names
"""data = [
    {'employee_id': '12', 'employee_name': 'sai'},
    {'employee_id': '27', 'employee_name': 'Kumar'},
    {'employee_id': '99', 'employee_name': 'venkat'},
    {'employee_id': '58', 'employee_name': 'shyam'},
    {'employee_id': '33', 'employee_name': 'rana'},
    {'employee_id': '86', 'employee_name': 'semwal'},
]
"""

data =[
    {'employee_id': '1', 'employee_name': 'Olivia'}, {'employee_id': '2', 'employee_name': 'Emma'}, {'employee_id': '3', 'employee_name': 'Ava'}, {'employee_id': '4', 'employee_name': 'Charlotte'}, {'employee_id': '5', 'employee_name': 'Sophia'},
    {'employee_id': '6', 'employee_name': 'Amelia'}, {'employee_id': '7', 'employee_name': 'Isabella'}, {'employee_id': '8', 'employee_name': 'Mia'}, 
    {'employee_id': '9', 'employee_name': 'Evelyn'}, {'employee_id': '10', 'employee_name': 'Harper'}, {'employee_id': '11', 'employee_name': 'Camila'}, {'employee_id': '12', 'employee_name': 'Gianna'},
    {'employee_id': '13', 'employee_name': 'Abigail'}, {'employee_id': '14', 'employee_name': 'Luna'}, {'employee_id': '15', 'employee_name': 'Ella'}, {'employee_id': '16', 'employee_name': 'Elizabeth'}, {'employee_id': '17', 'employee_name': 'Sofia'},
    {'employee_id': '18', 'employee_name': 'Emily'}, {'employee_id': '19', 'employee_name': 'Avery'}, {'employee_id': '20', 'employee_name': 'Mila'}, {'employee_id': '21', 'employee_name': 'Scarlett'}, {'employee_id': '22', 'employee_name': 'Eleanor'},
    {'employee_id': '23', 'employee_name': 'Madison'}, {'employee_id': '24', 'employee_name': 'Layla'}, {'employee_id': '25', 'employee_name': 'Penelope'}, {'employee_id': '26', 'employee_name': 'Aria'}, {'employee_id': '27', 'employee_name': 'Chloe'}, 
    {'employee_id': '28', 'employee_name': 'Grace'}, {'employee_id': '29', 'employee_name': 'Ellie'}, {'employee_id': '30', 'employee_name': 'Nora'}, {'employee_id': '31', 'employee_name': 'Hazel'}, {'employee_id': '32', 'employee_name': 'Zoey'},
    {'employee_id': '33', 'employee_name': 'Riley'}, {'employee_id': '34', 'employee_name': 'Victoria'}, {'employee_id': '35', 'employee_name': 'Lily'}, {'employee_id': '36', 'employee_name': 'Aurora'}, {'employee_id': '37', 'employee_name': 'Violet'},
    {'employee_id': '38', 'employee_name': 'Nova'}, {'employee_id': '39', 'employee_name': 'Hannah'}, {'employee_id': '40', 'employee_name': 'Emilia'}, {'employee_id': '41', 'employee_name': 'Zoe'}, {'employee_id': '42', 'employee_name': 'Stella'},
    {'employee_id': '43', 'employee_name': 'Everly'}, {'employee_id': '44', 'employee_name': 'Isla'}, {'employee_id': '45', 'employee_name': 'Leah'}, {'employee_id': '46', 'employee_name': 'Lillian'}, {'employee_id': '47', 'employee_name': 'Addison'},
    {'employee_id': '48', 'employee_name': 'Willow'}, {'employee_id': '49', 'employee_name': 'Lucy'}, {'employee_id': '50', 'employee_name': 'Paisley'}, {'employee_id': '51', 'employee_name': 'Natalie'}, {'employee_id': '52', 'employee_name': 'Naomi'}, 
    {'employee_id': '53', 'employee_name': 'Eliana'}, {'employee_id': '54', 'employee_name': 'Brooklyn'}, {'employee_id': '55', 'employee_name': 'Elena'}, {'employee_id': '56', 'employee_name': 'Aubrey'}, {'employee_id': '57', 'employee_name': 'Claire'}, 
    {'employee_id': '58', 'employee_name': 'Ivy'}, {'employee_id': '59', 'employee_name': 'Kinsley'}, {'employee_id': '60', 'employee_name': 'Audrey'}, {'employee_id': '61', 'employee_name': 'Maya'}, {'employee_id': '62', 'employee_name': 'Genesis'}, 
    {'employee_id': '63', 'employee_name': 'Skylar'}, {'employee_id': '64', 'employee_name': 'Bella'}, {'employee_id': '65', 'employee_name': 'Aaliyah'}, {'employee_id': '66', 'employee_name': 'Madelyn'}, {'employee_id': '67', 'employee_name': 'Savannah'}, 
    {'employee_id': '68', 'employee_name': 'Anna'}, {'employee_id': '69', 'employee_name': 'Delilah'}, {'employee_id': '70', 'employee_name': 'Serenity'}, {'employee_id': '71', 'employee_name': 'Caroline'}, {'employee_id': '72', 'employee_name': 'Kennedy'}, 
    {'employee_id': '73', 'employee_name': 'Valentina'}, {'employee_id': '74', 'employee_name': 'Ruby'}, {'employee_id': '75', 'employee_name': 'Sophie'}, {'employee_id': '76', 'employee_name': 'Alice'}, {'employee_id': '77', 'employee_name': 'Gabriella'}, 
    {'employee_id': '78', 'employee_name': 'Sadie'}, {'employee_id': '79', 'employee_name': 'Ariana'}, {'employee_id': '80', 'employee_name': 'Allison'}, {'employee_id': '81', 'employee_name': 'Hailey'}, {'employee_id': '82', 'employee_name': 'Autumn'}, 
    {'employee_id': '83', 'employee_name': 'Nevaeh'}, {'employee_id': '84', 'employee_name': 'Natalia'}, {'employee_id': '85', 'employee_name': 'Quinn'}, {'employee_id': '86', 'employee_name': 'Josephine'}, {'employee_id': '87', 'employee_name': 'Sarah'}, 
    {'employee_id': '88', 'employee_name': 'Cora'}, {'employee_id': '89', 'employee_name': 'Emery'}, {'employee_id': '90', 'employee_name': 'Samantha'}, {'employee_id': '91', 'employee_name': 'Piper'}, {'employee_id': '92', 'employee_name': 'Leilani'}, 
    {'employee_id': '93', 'employee_name': 'Eva'}, {'employee_id': '94', 'employee_name': 'Everleigh'}, {'employee_id': '95', 'employee_name': 'Madeline'}, {'employee_id': '96', 'employee_name': 'Lydia'}, {'employee_id': '97', 'employee_name': 'Jade'}, 
    {'employee_id': '98', 'employee_name': 'Peyton'}, {'employee_id': '99', 'employee_name': 'Brielle'}, {'employee_id': '100', 'employee_name': 'Adeline'}, {'employee_id': '101', 'employee_name': 'Vivian'}, {'employee_id': '102', 'employee_name': 'Rylee'}, 
    {'employee_id': '103', 'employee_name': 'Clara'}, {'employee_id': '104', 'employee_name': 'Raelynn'}, {'employee_id': '105', 'employee_name': 'Melanie'}, {'employee_id': '106', 'employee_name': 'Melody'}, {'employee_id': '107', 'employee_name': 'Julia'}, 
    {'employee_id': '108', 'employee_name': 'Athena'}, {'employee_id': '109', 'employee_name': 'Maria'}, {'employee_id': '110', 'employee_name': 'Liliana'}, {'employee_id': '111', 'employee_name': 'Hadley'}, {'employee_id': '112', 'employee_name': 'Arya'}, 
    {'employee_id': '113', 'employee_name': 'Rose'}, {'employee_id': '114', 'employee_name': 'Reagan'}, {'employee_id': '115', 'employee_name': 'Eliza'}, {'employee_id': '116', 'employee_name': 'Adalynn'}, {'employee_id': '117', 'employee_name': 'Kaylee'}, 
    {'employee_id': '118', 'employee_name': 'Lyla'}, {'employee_id': '119', 'employee_name': 'Mackenzie'}, {'employee_id': '120', 'employee_name': 'Alaia'}, {'employee_id': '121', 'employee_name': 'Isabelle'}, {'employee_id': '122', 'employee_name': 'Charlie'}, 
    {'employee_id': '123', 'employee_name': 'Arianna'}, {'employee_id': '124', 'employee_name': 'Mary'}, {'employee_id': '125', 'employee_name': 'Remi'}, {'employee_id': '126', 'employee_name': 'Margaret'}, {'employee_id': '127', 'employee_name': 'Iris'}, 
    {'employee_id': '128', 'employee_name': 'Parker'}, {'employee_id': '129', 'employee_name': 'Ximena'}, {'employee_id': '130', 'employee_name': 'Eden'}, {'employee_id': '131', 'employee_name': 'Ayla'}, {'employee_id': '132', 'employee_name': 'Kylie'}, 
    {'employee_id': '133', 'employee_name': 'Elliana'}, {'employee_id': '134', 'employee_name': 'Josie'}, {'employee_id': '135', 'employee_name': 'Katherine'}, {'employee_id': '136', 'employee_name': 'Faith'}, {'employee_id': '137', 'employee_name': 'Alexandra'}, 
    {'employee_id': '138', 'employee_name': 'Eloise'}, {'employee_id': '139', 'employee_name': 'Adalyn'}, {'employee_id': '140', 'employee_name': 'Amaya'}, {'employee_id': '141', 'employee_name': 'Jasmine'}, {'employee_id': '142', 'employee_name': 'Amara'}, 
    {'employee_id': '143', 'employee_name': 'Daisy'}, {'employee_id': '144', 'employee_name': 'Reese'}, {'employee_id': '145', 'employee_name': 'Valerie'}, {'employee_id': '146', 'employee_name': 'Brianna'}, {'employee_id': '147', 'employee_name': 'Cecilia'}, 
    {'employee_id': '148', 'employee_name': 'Andrea'}, {'employee_id': '149', 'employee_name': 'Summer'}, {'employee_id': '150', 'employee_name': 'Valeria'}, {'employee_id': '151', 'employee_name': 'Norah'}, {'employee_id': '152', 'employee_name': 'Ariella'}, 
    {'employee_id': '153', 'employee_name': 'Esther'}, {'employee_id': '154', 'employee_name': 'Ashley'}, {'employee_id': '155', 'employee_name': 'Emerson'}, {'employee_id': '156', 'employee_name': 'Aubree'}, {'employee_id': '157', 'employee_name': 'Isabel'}, 
    {'employee_id': '158', 'employee_name': 'Anastasia'}, {'employee_id': '159', 'employee_name': 'Ryleigh'}, {'employee_id': '160', 'employee_name': 'Khloe'}, {'employee_id': '161', 'employee_name': 'Taylor'}, {'employee_id': '162', 'employee_name': 'Londyn'}, 
    {'employee_id': '163', 'employee_name': 'Lucia'}, {'employee_id': '164', 'employee_name': 'Emersyn'}, {'employee_id': '165', 'employee_name': 'Callie'}, {'employee_id': '166', 'employee_name': 'Sienna'}, {'employee_id': '167', 'employee_name': 'Blakely'}, 
    {'employee_id': '168', 'employee_name': 'Ana'}, {'employee_id': '169', 'employee_name': 'Genevieve'}, {'employee_id': '170', 'employee_name': 'Kathleen'}, {'employee_id': '171', 'employee_name': 'Payton'}, {'employee_id': '172', 'employee_name': 'Sawyer'}, 
    {'employee_id': '173', 'employee_name': 'Paige'}, {'employee_id': '174', 'employee_name': 'Nova'}, {'employee_id': '175', 'employee_name': 'Emery'}, {'employee_id': '176', 'employee_name': 'Mckenzie'}, {'employee_id': '177', 'employee_name': 'Mariah'}, 
    {'employee_id': '178', 'employee_name': 'Genesis'}, {'employee_id': '179', 'employee_name': 'Bella'}, {'employee_id': '180', 'employee_name': 'Aurora'}, 
    {'employee_id': '181', 'employee_name': 'Giselle'}, {'employee_id': '182', 'employee_name': 'Athena'}, {'employee_id': '183', 'employee_name': 'Freya'}, {'employee_id': '184', 'employee_name': 'Kiara'}, {'employee_id': '185', 'employee_name': 'Delaney'}, 
    {'employee_id': '186', 'employee_name': 'Ophelia'}, {'employee_id': '187', 'employee_name': 'Kaitlyn'}, {'employee_id': '188', 'employee_name': 'Cecelia'}, {'employee_id': '189', 'employee_name': 'Lia'}, {'employee_id': '190', 'employee_name': 'Juliette'}, 
    {'employee_id': '191', 'employee_name': 'Diana'}, {'employee_id': '192', 'employee_name': 'Georgia'}, {'employee_id': '193', 'employee_name': 'Jane'}, {'employee_id': '194', 'employee_name': 'Eden'}, {'employee_id': '195', 'employee_name': 'Elise'}, 
    {'employee_id': '196', 'employee_name': 'Alexandra'}, {'employee_id': '197', 'employee_name': 'Natalia'}, {'employee_id': '198', 'employee_name': 'Hadley'}, {'employee_id': '199', 'employee_name': 'Lydia'}, {'employee_id': '200', 'employee_name': 'Reagan'},
    {'employee_id': '201', 'employee_name': 'Isha'}, {'employee_id': '202', 'employee_name': 'Smt Shyani Devi'}, {'employee_id': '203', 'employee_name': 'Divya'}, {'employee_id': '204', 'employee_name': 'Mansi'}, {'employee_id': '205', 'employee_name': 'Mazida'}, 
    {'employee_id': '206', 'employee_name': 'Pooja'}, {'employee_id': '207', 'employee_name': 'Kajal'}, {'employee_id': '208', 'employee_name': 'Meena'}, {'employee_id': '209', 'employee_name': 'Sonam'}, {'employee_id': '210', 'employee_name': 'Buity'}, 
    {'employee_id': '211', 'employee_name': 'Hina'}, {'employee_id': '212', 'employee_name': 'Shakshi Sagar'}, {'employee_id': '213', 'employee_name': 'Anita'}, {'employee_id': '214', 'employee_name': 'Neetu'}, {'employee_id': '215', 'employee_name': 'Anshu'}, 
    {'employee_id': '216', 'employee_name': 'Kanika Kathuria'}, {'employee_id': '217', 'employee_name': 'Manju'}, {'employee_id': '218', 'employee_name': 'Shakshi'}, {'employee_id': '219', 'employee_name': 'Anita'}, {'employee_id': '220', 'employee_name': 'Reena'}, 
    {'employee_id': '221', 'employee_name': 'Neha'}, {'employee_id': '222', 'employee_name': 'Khushboo'}, {'employee_id': '223', 'employee_name': 'Aasmin'}, {'employee_id': '224', 'employee_name': 'Jyoti'}, {'employee_id': '225', 'employee_name': 'Riya Masi'}, 
    {'employee_id': '226', 'employee_name': 'Rekha'}, {'employee_id': '227', 'employee_name': 'Leela (with a child)'}, {'employee_id': '228', 'employee_name': 'Isha'}, {'employee_id': '229', 'employee_name': 'Gulshan'}, {'employee_id': '230', 'employee_name': 'Priya Jain'}, 
    {'employee_id': '231', 'employee_name': 'Pooja'}, {'employee_id': '232', 'employee_name': 'Rakhi'}, {'employee_id': '233', 'employee_name': 'Versha'}, {'employee_id': '234', 'employee_name': 'Sunita'}, {'employee_id': '235', 'employee_name': 'Nitu Kumari'}, 
    {'employee_id': '236', 'employee_name': 'Vandana'}, {'employee_id': '237', 'employee_name': 'Roshni'}, {'employee_id': '238', 'employee_name': 'Parveen'}, {'employee_id': '239', 'employee_name': 'Versa'}, {'employee_id': '240', 'employee_name': 'Kavita'}, 
    {'employee_id': '241', 'employee_name': 'Pooja'}, {'employee_id': '242', 'employee_name': 'Sarojani'}, {'employee_id': '243', 'employee_name': 'Nagina'}, {'employee_id': '244', 'employee_name': 'Tapas Das'}, {'employee_id': '245', 'employee_name': 'Priyanka'}, 
    {'employee_id': '246', 'employee_name': 'Santna'}, {'employee_id': '247', 'employee_name': 'Khushbu'}, {'employee_id': '248', 'employee_name': 'Pooja'}, {'employee_id': '249', 'employee_name': 'Any Bobby'}, {'employee_id': '250', 'employee_name': 'Deeya Kumari'}, 
    {'employee_id': '251', 'employee_name': 'Anjali Juneja'}, {'employee_id': '252', 'employee_name': 'Anjali (Babli)'}, {'employee_id': '253', 'employee_name': 'Champa Karketta'}, {'employee_id': '254', 'employee_name': 'Anshu'}, 
    {'employee_id': '255', 'employee_name': 'Monika'}, {'employee_id': '256', 'employee_name': 'Rimmi Singh'}, {'employee_id': '257', 'employee_name': 'Aanamika Misra'}, {'employee_id': '258', 'employee_name': 'Chahat'}, 
    {'employee_id': '259', 'employee_name': 'Manju'}, {'employee_id': '260', 'employee_name': 'Nagma Khatoon'}, {'employee_id': '261', 'employee_name': 'Pooja'}, {'employee_id': '262', 'employee_name': 'Sonam'}, {'employee_id': '263', 'employee_name': 'Koshal'}, 
    {'employee_id': '264', 'employee_name': 'Laxmi Devi (wife of late Sh. Hukan Chand)'}, {'employee_id': '265', 'employee_name': 'Sandhya'}, {'employee_id': '266', 'employee_name': 'Poonam'}, {'employee_id': '267', 'employee_name': 'Sna'}, {'employee_id': '268', 'employee_name': 'Nikita Senger'}, 
    {'employee_id': '269', 'employee_name': 'Layba Noor'}, {'employee_id': '270', 'employee_name': 'Iqra'}, {'employee_id': '271', 'employee_name': 'Salima'}, {'employee_id': '272', 'employee_name': 'Naziya Siddiqui'}, {'employee_id': '273', 'employee_name': 'Priti'}, 
    {'employee_id': '274', 'employee_name': 'Kamni'}, {'employee_id': '275', 'employee_name': 'Sandhya'}, {'employee_id': '276', 'employee_name': 'Renu (Rinki)'}, {'employee_id': '277', 'employee_name': 'Priya'}, {'employee_id': '278', 'employee_name': 'Pooja'}, {'employee_id': '279', 'employee_name': 'Minakchi'}, 
    {'employee_id': '280', 'employee_name': 'Ruby'}, {'employee_id': '281', 'employee_name': 'Smt. Farhana Baigum'}, {'employee_id': '282', 'employee_name': 'Sheetal'}, {'employee_id': '283', 'employee_name': 'Kalyani Patro'}, {'employee_id': '284', 'employee_name': 'Anjali'}, 
    {'employee_id': '285', 'employee_name': 'Priyanka'}, {'employee_id': '286', 'employee_name': 'Palak (Simran)'}, {'employee_id': '287', 'employee_name': 'Babita'}, {'employee_id': '288', 'employee_name': 'Gurdeep Kaur'}, {'employee_id': '289', 'employee_name': 'Dhanwanti Devi'}, 
    {'employee_id': '290', 'employee_name': 'Fooljhnah'}, {'employee_id': '291', 'employee_name': 'Vandana'}, {'employee_id': '292', 'employee_name': 'Smt. Gyatri Devi'}, {'employee_id': '293', 'employee_name': 'Shehnaz'}, {'employee_id': '294', 'employee_name': 'Kajal'}, {'employee_id': '295', 'employee_name': 'Pooja'}, 
    {'employee_id': '296', 'employee_name': 'Ranju'}, {'employee_id': '297', 'employee_name': 'Vidhi'}, {'employee_id': '298', 'employee_name': 'Pooja Kashyap'}, {'employee_id': '299', 'employee_name': 'Jyoti'}, {'employee_id': '300', 'employee_name': 'Meena Kumari'}, 
    {'employee_id': '301', 'employee_name': 'Savita, Sagar, Panap'}, {'employee_id': '302', 'employee_name': 'Reena Devi'}, {'employee_id': '303', 'employee_name': 'Neha'}, 
    {'employee_id': '304', 'employee_name': 'Payal Goyala'}, {'employee_id': '305', 'employee_name': 'Rakhi'}, {'employee_id': '306', 'employee_name': 'Priynka'}, {'employee_id': '307', 'employee_name': 'Janki'}, {'employee_id': '308', 'employee_name': 'Laxmi Kumari'}, 
    {'employee_id': '309', 'employee_name': 'Rinku Malav'}, {'employee_id': '310', 'employee_name': 'Sohni'}, {'employee_id': '311', 'employee_name': 'Basnti'}, {'employee_id': '312', 'employee_name': 'Meera'}, {'employee_id': '313', 'employee_name': 'Pinki'}, {'employee_id': '314', 'employee_name': 'Shivani'}, 
    {'employee_id': '315', 'employee_name': 'Kiran Devi'}, {'employee_id': '316', 'employee_name': 'Sonia'}, {'employee_id': '317', 'employee_name': 'Doly'}, {'employee_id': '318', 'employee_name': 'Raj Kumari'}, {'employee_id': '319', 'employee_name': 'Manisha'}, {'employee_id': '320', 'employee_name': 'Laxmi Devi'}, 
    {'employee_id': '321', 'employee_name': 'Swati Joshi'},{'employee_id': '322', 'employee_name': 'Barjraj'}, {'employee_id': '323', 'employee_name': 'Ramdin Verma'}, {'employee_id': '324', 'employee_name': 'Sharat Chandran'}, {'employee_id': '325', 'employee_name': 'Birender Mandal'}, {'employee_id': '326', 'employee_name': 'Amit'}, {'employee_id': '327', 'employee_name': 'Kushal'}, 
    {'employee_id': '328', 'employee_name': 'Kasid'}, {'employee_id': '329', 'employee_name': 'Shiv Prakash'}, {'employee_id': '330', 'employee_name': 'Vikram Singh'}, {'employee_id': '331', 'employee_name': 'Sanjay'}, {'employee_id': '332', 'employee_name': 'Abhi'}, {'employee_id': '333', 'employee_name': 'Ram Dutt Gupta'}, {'employee_id': '334', 'employee_name': 'Khadak Singh'}, {'employee_id': '335', 'employee_name': 'Gurmit Singh'}, {'employee_id': '336', 'employee_name': 'Chanderpal'}, {'employee_id': '337', 'employee_name': 'Aman'}, 
    {'employee_id': '338', 'employee_name': 'Khursid'}, {'employee_id': '339', 'employee_name': 'Rajeev'}, 
    {'employee_id': '340', 'employee_name': 'Durgesh'}, {'employee_id': '341', 'employee_name': 'Nahar Singh'}, {'employee_id': '342', 'employee_name': 'Ram Kumar'}, {'employee_id': '343', 'employee_name': 'Sunder Paal'}, 
    {'employee_id': '344', 'employee_name': 'Maansingh Aswal'}, {'employee_id': '345', 'employee_name': 'Rohit'}, {'employee_id': '346', 'employee_name': 'Sparsh'}, {'employee_id': '347', 'employee_name': 'Santosh'}, {'employee_id': '348', 'employee_name': 'Punit Khandelwal'}, {'employee_id': '349', 'employee_name': 'Dinesh'}, {'employee_id': '350', 'employee_name': 'Gulshan'}, 
    {'employee_id': '351', 'employee_name': 'Arvind Kumar Yadav'}, {'employee_id': '352', 'employee_name': 'Nausad'}, {'employee_id': '353', 'employee_name': 'Md. Afsar'}, {'employee_id': '354', 'employee_name': 'Shiv Shakti Singh'}, {'employee_id': '355', 'employee_name': 'Moti Lal'}, {'employee_id': '356', 'employee_name': 'Kausal Kumar'}, 
    {'employee_id': '357', 'employee_name': 'Mohabbat Ali'}, {'employee_id': '358', 'employee_name': 'Raj Kumar'}, {'employee_id': '359', 'employee_name': 'Jaswant Singh'}, {'employee_id': '360', 'employee_name': 'Sevak @ Pitambar Lal'}, {'employee_id': '361', 'employee_name': 'Chotelal'}, {'employee_id': '362', 'employee_name': 'Rupesh'}, {'employee_id': '363', 'employee_name': 'Midda'}, 
    {'employee_id': '364', 'employee_name': 'Dharam Singh'}, {'employee_id': '365', 'employee_name': 'Manoj Yadav @ Manoj'}, {'employee_id': '366', 'employee_name': 'Ram Singh'}, {'employee_id': '367', 'employee_name': 'Preetam Kumar'}, {'employee_id': '368', 'employee_name': 'Sarain'}, {'employee_id': '369', 'employee_name': 'Pankaj Kumar'}, 
    {'employee_id': '370', 'employee_name': 'Sheak Shakir'}, {'employee_id': '371', 'employee_name': 'Riyasat Ali'}, {'employee_id': '372', 'employee_name': 'Vinit Katariya'}, {'employee_id': '373', 'employee_name': 'Sumit'}, {'employee_id': '374', 'employee_name': 'Arindra'}, {'employee_id': '375', 'employee_name': 'Kali Charan'}, {'employee_id': '376', 'employee_name': 'Badshya Khan'}, {'employee_id': '377', 'employee_name': 'Vikash'}, 
    {'employee_id': '378', 'employee_name': 'Devinder Chadda'}, {'employee_id': '379', 'employee_name': 'Mohan Singh'}, {'employee_id': '380', 'employee_name': 'Hemant'}, {'employee_id': '381', 'employee_name': 'Shivam'}, {'employee_id': '382', 'employee_name': 'Yash Mittal'}, {'employee_id': '383', 'employee_name': 'Aakash'}, {'employee_id': '384', 'employee_name': 'Chandesh'}, 
    {'employee_id': '385', 'employee_name': 'Supriyal Sen'}, {'employee_id': '386', 'employee_name': 'Gajender Singh @ Goldy'}, {'employee_id': '387', 'employee_name': 'Pooran Chand Sharma'}, {'employee_id': '388', 'employee_name': 'Irfan'}, {'employee_id': '389', 'employee_name': 'Azaruddin'}, {'employee_id': '390', 'employee_name': 'Mukul Yadav'}, {'employee_id': '391', 'employee_name': 'Manoj'}, {'employee_id': '392', 'employee_name': 'Sanjay Charee'}, 
    {'employee_id': '393', 'employee_name': 'Raja Babu'}, {'employee_id': '394', 'employee_name': 'Pawan'}, {'employee_id': '395', 'employee_name': 'Sandeep'}, {'employee_id': '396', 'employee_name': 'Rajkumar Chawla'}, {'employee_id': '397', 'employee_name': 'Parvesh'}, {'employee_id': '398', 'employee_name': 'Mohd Ataullah'}, {'employee_id': '399', 'employee_name': 'Neeraj Kumar'}, {'employee_id': '400', 'employee_name': 'Jamil Khan'}, {'employee_id': '401', 'employee_name': 'Yogita'}, 
    {'employee_id': '402', 'employee_name': 'Rijul Aggarwal'}, {'employee_id': '403', 'employee_name': 'Mohd Shakib'}, {'employee_id': '404', 'employee_name': 'Rahul Kumar'}, {'employee_id': '405', 'employee_name': 'Rajender'}, {'employee_id': '406', 'employee_name': 'Suraj'}, {'employee_id': '407', 'employee_name': 'Rizwan'}, {'employee_id': '408', 'employee_name': 'Md Mustafa'}, {'employee_id': '409', 'employee_name': 'Har Parsad'}, {'employee_id': '410', 'employee_name': 'Deepak'}, {'employee_id': '411', 'employee_name': 'Rahul'}, {'employee_id': '412', 'employee_name': 'Abhishekh'}, {'employee_id': '413', 'employee_name': 'Shelender Yadav'}, 
    {'employee_id': '414', 'employee_name': 'Ankit'}, {'employee_id': '415', 'employee_name': 'Mohd Aakib'}, {'employee_id': '416', 'employee_name': 'Surender Singh Chauhan'}, {'employee_id': '417', 'employee_name': 'Arjun'}, {'employee_id': '418', 'employee_name': 'Rahul Sharma'}, {'employee_id': '419', 'employee_name': 'Keshar Ansari'}, {'employee_id': '420', 'employee_name': 'Raju @ Chhotu'}, {'employee_id': '421', 'employee_name': 'Kuldeep Singh'}, {'employee_id': '422', 'employee_name': 'Santlal @ Golu'}, {'employee_id': '423', 'employee_name': 'Lalit Rana'}, {'employee_id': '424', 'employee_name': 'Pulkit Sharma'}, {'employee_id': '425', 'employee_name': 'Aman Soni @ Badal'}, {'employee_id': '426', 'employee_name': 'Jahoor Ahmed Meer'}, {'employee_id': '427', 'employee_name': 'Tammanne'}, {'employee_id': '428', 'employee_name': 'Kailash Kumar'}, {'employee_id': '429', 'employee_name': 'Bhagwati Prasad'}, {'employee_id': '430', 'employee_name': 'Ajay'}, {'employee_id': '431', 'employee_name': 'Silender'}, {'employee_id': '432', 'employee_name': 'Deepak'}, {'employee_id': '433', 'employee_name': 'Akhilesh'}, {'employee_id': '434', 'employee_name': 'Dipendra Kumar'}, {'employee_id': '435', 'employee_name': 'Nitin'}, {'employee_id': '436', 'employee_name': 'Doodhnath Pandit'}, {'employee_id': '437', 'employee_name': 'Aslam Allam'}, {'employee_id': '438', 'employee_name': 'Rahul'}, 
    {'employee_id': '439', 'employee_name': 'Jitender'}, {'employee_id': '440', 'employee_name': 'Sandeep Sharma'}, {'employee_id': '441', 'employee_name': 'Ravindra Kumar'}, {'employee_id': '442', 'employee_name': 'Anil Kumar'}, {'employee_id': '443', 'employee_name': 'Harish'}, {'employee_id': '444', 'employee_name': 'Kamal'}, {'employee_id': '445', 'employee_name': 'Vishal'}, {'employee_id': '446', 'employee_name': 'Manish'}, {'employee_id': '447', 'employee_name': 'Suresh Kumar'}, {'employee_id': '448', 'employee_name': 'Ramesh'}, {'employee_id': '449', 'employee_name': 'Vijay'}, {'employee_id': '450', 'employee_name': 'Rajesh'}, {'employee_id': '451', 'employee_name': 'Ajay Kumar'}, {'employee_id': '452', 'employee_name': 'Praveen Kumar'}, {'employee_id': '453', 'employee_name': 'Ravi Kumar'}, {'employee_id': '454', 'employee_name': 'Rakesh'}, {'employee_id': '455', 'employee_name': 'Arun Kumar'}, {'employee_id': '456', 'employee_name': 'Anil'}, {'employee_id': '457', 'employee_name': 'Satish'}, {'employee_id': '458', 'employee_name': 'Sunil'}, {'employee_id': '459', 'employee_name': 'Vikas'}, {'employee_id': '460', 'employee_name': 'Alok'}, {'employee_id': '461', 'employee_name': 'Vinod'}, {'employee_id': '462', 'employee_name': 'Amit Kumar'}, {'employee_id': '463', 'employee_name': 'Sanjeev'}, {'employee_id': '464', 'employee_name': 'Pradeep'}, {'employee_id': '465', 'employee_name': 'Rahul Verma'}, {'employee_id': '466', 'employee_name': 'Mukesh Kumar'}, {'employee_id': '467', 'employee_name': 'Naresh'}, 
    {'employee_id': '468', 'employee_name': 'Deepak Kumar'}, {'employee_id': '469', 'employee_name': 'Anuj'}, {'employee_id': '470', 'employee_name': 'Pankaj'}, {'employee_id': '471', 'employee_name': 'Rajiv'}, {'employee_id': '472', 'employee_name': 'Ashok'}, {'employee_id': '473', 'employee_name': 'Anoop'}, {'employee_id': '474', 'employee_name': 'Naveen'}, {'employee_id': '475', 'employee_name': 'Ankit Kumar'}, {'employee_id': '476', 'employee_name': 'Amit Sharma'}, {'employee_id': '477', 'employee_name': 'Sachin'}, {'employee_id': '478', 'employee_name': 'Amar'}, {'employee_id': '479', 'employee_name': 'Gaurav'}, {'employee_id': '480', 'employee_name': 'Sandeep Kumar'}, {'employee_id': '481', 'employee_name': 'Nitin Kumar'}, {'employee_id': '482', 'employee_name': 'Mohit'}, {'employee_id': '483', 'employee_name': 'Saurabh'}, {'employee_id': '484', 'employee_name': 'Vivek'}, {'employee_id': '485', 'employee_name': 'Vijay Kumar'}, {'employee_id': '486', 'employee_name': 'Ashish'}, {'employee_id': '487', 'employee_name': 'Manoj Kumar'}, {'employee_id': '488', 'employee_name': 'Avinash'}, {'employee_id': '489', 'employee_name': 'Rajeev Kumar'}, {'employee_id': '490', 'employee_name': 'Gopal'}, {'employee_id': '491', 'employee_name': 'Manish Kumar'}, {'employee_id': '492', 'employee_name': 'Ajeet'}, {'employee_id': '493', 'employee_name': 'Dinesh Kumar'}, {'employee_id': '494', 'employee_name': 'Sumit Kumar'}, {'employee_id': '495', 'employee_name': 'Sarvesh'}, {'employee_id': '496', 'employee_name': 'Mahesh'}, {'employee_id': '497', 'employee_name': 'Pramod'}, {'employee_id': '498', 'employee_name': 'Pankaj Kumar'}, {'employee_id': '499', 'employee_name': 'Pardeep'}, {'employee_id': '500', 'employee_name': 'Sudhir'}, 
    {'employee_id': '501', 'employee_name': 'Naveen Kumar'}, {'employee_id': '502', 'employee_name': 'Rahul Singh'}, {'employee_id': '503', 'employee_name': 'Lalit Kumar'}, {'employee_id': '504', 'employee_name': 'Prashant'}, {'employee_id': '505', 'employee_name': 'Arvind Kumar'}, {'employee_id': '506', 'employee_name': 'Rajinder'}, {'employee_id': '507', 'employee_name': 'Rakesh Kumar'}, {'employee_id': '508', 'employee_name': 'Rohit Kumar'}, {'employee_id': '509', 'employee_name': 'Shiv Kumar'}, {'employee_id': '510', 'employee_name': 'Hari'}, {'employee_id': '511', 'employee_name': 'Narendra'}, {'employee_id': '512', 'employee_name': 'Raj'}, {'employee_id': '513', 'employee_name': 'Jitendra'}, {'employee_id': '514', 'employee_name': 'Vishnu'}, {'employee_id': '515', 'employee_name': 'Pawan Kumar'}, {'employee_id': '516', 'employee_name': 'Anand'}, {'employee_id': '517', 'employee_name': 'Naveen Sharma'}, {'employee_id': '518', 'employee_name': 'Ashok Kumar'}, {'employee_id': '519', 'employee_name': 'Vipin'}, {'employee_id': '520', 'employee_name': 'Ankit Singh'}, {'employee_id': '521', 'employee_name': 'Ajay Kumar'}, {'employee_id': '522', 'employee_name': 'Rajkumar'}, {'employee_id': '523', 'employee_name': 'Sushil Kumar'}, {'employee_id': '524', 'employee_name': 'Rahul Gupta'}, {'employee_id': '525', 'employee_name': 'Deepak Singh'}, {'employee_id': '526', 'employee_name': 'Shiv Shankar'}, {'employee_id': '527', 'employee_name': 'Amit Kumar Verma'}, {'employee_id': '528', 'employee_name': 'Rajeev Kumar'}, {'employee_id': '529', 'employee_name': 'Rajesh Kumar'}, {'employee_id': '530', 'employee_name': 'Rajendra'}, {'employee_id': '531', 'employee_name': 'Prakash'}, {'employee_id': '532', 'employee_name': 'Sanjay Kumar'}, {'employee_id': '533', 'employee_name': 'Ranjeet'}, {'employee_id': '534', 'employee_name': 'Dheeraj'}, {'employee_id': '535', 'employee_name': 'Surender'}, {'employee_id': '536', 'employee_name': 'Pramod Kumar'}, {'employee_id': '537', 'employee_name': 'Pawan Kumar Verma'}, 
    {'employee_id': '538', 'employee_name': 'Ajay Verma'}, {'employee_id': '539', 'employee_name': 'Ravindra'}, {'employee_id': '540', 'employee_name': 'Yogesh'}, {'employee_id': '541', 'employee_name': 'Ankit Verma'}, {'employee_id': '542', 'employee_name': 'Anurag'}, {'employee_id': '543', 'employee_name': 'Raju'}, {'employee_id': '544', 'employee_name': 'Ankit Kumar Verma'}, {'employee_id': '545', 'employee_name': 'Santosh Kumar'}, {'employee_id': '546', 'employee_name': 'Ashutosh'}, {'employee_id': '547', 'employee_name': 'Rahul Verma'}, {'employee_id': '548', 'employee_name': 'Arjun Singh'}, {'employee_id': '549', 'employee_name': 'Satish Kumar'}, {'employee_id': '550', 'employee_name': 'Ajit'}, {'employee_id': '551', 'employee_name': 'Vijay Verma'}, {'employee_id': '552', 'employee_name': 'Rajneesh'}, {'employee_id': '553', 'employee_name': 'Praveen'}, {'employee_id': '554', 'employee_name': 'Deepak Verma'}, {'employee_id': '555', 'employee_name': 'Rajesh Verma'}, {'employee_id': '556', 'employee_name': 'Sachin Kumar'}, {'employee_id': '557', 'employee_name': 'Vijay Kumar Verma'}, {'employee_id': '558', 'employee_name': 'Sanjay Verma'}, {'employee_id': '559', 'employee_name': 'Ravi'}, {'employee_id': '560', 'employee_name': 'Anil Kumar Verma'}, {'employee_id': '561', 'employee_name': 'Sarvesh Kumar Verma'}, {'employee_id': '562', 'employee_name': 'Raj Kumar Verma'}, 
    {'employee_id': '563', 'employee_name': 'Pankaj Verma'}, {'employee_id': '564', 'employee_name': 'Arun Kumar Verma'}, {'employee_id': '565', 'employee_name': 'Nitin'}, {'employee_id': '566', 'employee_name': 'Rakesh Verma'}, {'employee_id': '567', 'employee_name': 'Sanjeev Kumar Verma'}, {'employee_id': '568', 'employee_name': 'Avinash Kumar Verma'}, {'employee_id': '569', 'employee_name': 'Manoj Kumar Verma'}, {'employee_id': '570', 'employee_name': 'Ashok Kumar Verma'}, {'employee_id': '571', 'employee_name': 'Amar Kumar Verma'}, {'employee_id': '572', 'employee_name': 'Vikas Verma'}, {'employee_id': '573', 'employee_name': 'Vinod Kumar Verma'}, {'employee_id': '574', 'employee_name': 'Gaurav Verma'}, {'employee_id': '575', 'employee_name': 'Vivek Verma'}, {'employee_id': '576', 'employee_name': 'Anuj Kumar Verma'}, {'employee_id': '577', 'employee_name': 'Rajeev Verma'}, {'employee_id': '578', 'employee_name': 'Narendra Kumar Verma'}, {'employee_id': '579', 'employee_name': 'Pradeep Verma'}, {'employee_id': '580', 'employee_name': 'Santosh Verma'}, {'employee_id': '581', 'employee_name': 'Sandeep Kumar Verma'}, {'employee_id': '582', 'employee_name': 'Rohit Verma'}, {'employee_id': '583', 'employee_name': 'Ravi Kumar Verma'}, {'employee_id': '584', 'employee_name': 'Anand Kumar Verma'}, 
    {'employee_id': '585', 'employee_name': 'Vipin Verma'}, {'employee_id': '586', 'employee_name': 'Ankit Verma'}, {'employee_id': '587', 'employee_name': 'Arvind Kumar Verma'}, {'employee_id': '588', 'employee_name': 'Vijay Kumar Verma'}, {'employee_id': '589', 'employee_name': 'Sumit Verma'}, {'employee_id': '590', 'employee_name': 'Ashish Kumar Verma'}, {'employee_id': '591', 'employee_name': 'Prashant Verma'}, {'employee_id': '592', 'employee_name': 'Rajesh Verma'}, {'employee_id': '593', 'employee_name': 'Yogesh Verma'}, {'employee_id': '594', 'employee_name': 'Ranjeet Verma'}, {'employee_id': '595', 'employee_name': 'Pawan Verma'}, {'employee_id': '596', 'employee_name': 'Rahul Verma'}, {'employee_id': '597', 'employee_name': 'Amit Verma'}, {'employee_id': '598', 'employee_name': 'Sushil Verma'}, {'employee_id': '599', 'employee_name': 'Dheeraj Verma'}, {'employee_id': '600', 'employee_name': 'Sanjay Verma'}, {'employee_id': '601', 'employee_name': 'Surender Verma'}, {'employee_id': '602', 'employee_name': 'Pramod Verma'}, {'employee_id': '603', 'employee_name': 'Rajneesh Verma'}, {'employee_id': '604', 'employee_name': 'Rajendra Verma'}, 
    {'employee_id': '605', 'employee_name': 'Anurag Verma'}, {'employee_id': '606', 'employee_name': 'Raj Verma'}, {'employee_id': '607', 'employee_name': 'Rajneesh Kumar Verma'}, {'employee_id': '608', 'employee_name': 'Raju Verma'}, {'employee_id': '609', 'employee_name': 'Ankit Verma'}, {'employee_id': '610', 'employee_name': 'Ravindra Verma'}, {'employee_id': '611', 'employee_name': 'Satish Verma'}, {'employee_id': '612', 'employee_name': 'Ajay Verma'}, {'employee_id': '613', 'employee_name': 'Anil Verma'}, {'employee_id': '614', 'employee_name': 'Ajay Kumar Verma'}, {'employee_id': '615', 'employee_name': 'Sachin Verma'}, {'employee_id': '616', 'employee_name': 'Praveen Verma'}, {'employee_id': '617', 'employee_name': 'Rajesh Kumar Verma'}, 
    {'employee_id': '618', 'employee_name': 'Nitin Verma'}, {'employee_id': '619', 'employee_name': 'Ajit Verma'}, {'employee_id': '620', 'employee_name': 'Anand Verma'}, {'employee_id': '621', 'employee_name': 'Naveen Verma'}, {'employee_id': '622', 'employee_name': 'Pradeep Kumar Verma'}, {'employee_id': '623', 'employee_name': 'Anil Kumar Verma'}, {'employee_id': '624', 'employee_name': 'Pankaj Kumar Verma'}, {'employee_id': '625', 'employee_name': 'Ashutosh Verma'}, {'employee_id': '626', 'employee_name': 'Manoj Verma'}, {'employee_id': '627', 'employee_name': 'Sanjeev Verma'}, {'employee_id': '628', 'employee_name': 'Amar Verma'}, {'employee_id': '629', 'employee_name': 'Gaurav Kumar Verma'}, {'employee_id': '630', 'employee_name': 'Rahul Kumar Verma'}, {'employee_id': '631', 'employee_name': 'Rajesh Kumar Verma'}, {'employee_id': '632', 'employee_name': 'Vinod Verma'}, {'employee_id': '633', 'employee_name': 'Deepak Kumar Verma'}, {'employee_id': '634', 'employee_name': 'Rohit Kumar Verma'}, {'employee_id': '635', 'employee_name': 'Avinash Verma'}, 
    {'employee_id': '636', 'employee_name': 'Vivek Kumar Verma'}, {'employee_id': '637', 'employee_name': 'Rajesh Verma'}, {'employee_id': '638', 'employee_name': 'Vikas Kumar Verma'}, {'employee_id': '639', 'employee_name': 'Rakesh Kumar Verma'}, {'employee_id': '640', 'employee_name': 'Anuj Verma'}, {'employee_id': '641', 'employee_name': 'Santosh Kumar Verma'}, {'employee_id': '642', 'employee_name': 'Ankit Kumar Verma'}, {'employee_id': '643', 'employee_name': 'Rajeev Kumar Verma'}, {'employee_id': '644', 'employee_name': 'Sandeep Kumar Verma'}, {'employee_id': '645', 'employee_name': 'Gopal Verma'}, {'employee_id': '646', 'employee_name': 'Manish Verma'}, {'employee_id': '647', 'employee_name': 'Ajeet Verma'}, {'employee_id': '648', 'employee_name': 'Dinesh Verma'}, {'employee_id': '649', 'employee_name': 'Sumit Verma'}, {'employee_id': '650', 'employee_name': 'Sarvesh Verma'}, {'employee_id': '651', 'employee_name': 'Mahesh Verma'}, {'employee_id': '652', 'employee_name': 'Pramod Kumar Verma'}, {'employee_id': '653', 'employee_name': 'Pankaj Verma'}, {'employee_id': '654', 'employee_name': 'Pardeep Verma'}, {'employee_id': '655', 'employee_name': 'Sudhir Verma'}, 
    {'employee_id': '656', 'employee_name': 'Naveen Kumar Verma'}, {'employee_id': '657', 'employee_name': 'Rahul Singh Verma'}, {'employee_id': '658', 'employee_name': 'Lalit Verma'}, {'employee_id': '659', 'employee_name': 'Prashant Verma'}, {'employee_id': '660', 'employee_name': 'Arvind Verma'}, {'employee_id': '661', 'employee_name': 'Rajinder Verma'}, {'employee_id': '662', 'employee_name': 'Rakesh Kumar Verma'}, {'employee_id': '663', 'employee_name': 'Shiv Kumar Verma'}, {'employee_id': '664', 'employee_name': 'Hari Verma'}, {'employee_id': '665', 'employee_name': 'Narendra Verma'}, {'employee_id': '666', 'employee_name': 'Raj Verma'}, {'employee_id': '667', 'employee_name': 'Jitendra Verma'}, {'employee_id': '668', 'employee_name': 'Vishnu Verma'}, {'employee_id': '669', 'employee_name': 'Pawan Verma'}, {'employee_id': '670', 'employee_name': 'Anand Verma'}, {'employee_id': '671', 'employee_name': 'Naveen Kumar Verma'}, {'employee_id': '672', 'employee_name': 'Ashok Verma'}, {'employee_id': '673', 'employee_name': 'Vipin Verma'}, {'employee_id': '674', 'employee_name': 'Ankit Singh Verma'}, 
    {'employee_id': '675', 'employee_name': 'Ajay Kumar Verma'}, {'employee_id': '676', 'employee_name': 'Rajkumar Verma'}, {'employee_id': '677', 'employee_name': 'Sushil Verma'}, {'employee_id': '678', 'employee_name': 'Rahul Gupta Verma'}, {'employee_id': '679', 'employee_name': 'Deepak Singh Verma'}, {'employee_id': '680', 'employee_name': 'Shiv Shankar Verma'}, {'employee_id': '681', 'employee_name': 'Amit Kumar Verma'}, {'employee_id': '682', 'employee_name': 'Rajeev Kumar Verma'}, {'employee_id': '683', 'employee_name': 'Rajesh Kumar Verma'}, {'employee_id': '684', 'employee_name': 'Rajendra Verma'}, {'employee_id': '685', 'employee_name': 'Prakash Verma'}, {'employee_id': '686', 'employee_name': 'Sanjay Kumar Verma'}, {'employee_id': '687', 'employee_name': 'Ranjeet Verma'}, {'employee_id': '688', 'employee_name': 'Dheeraj Verma'}, {'employee_id': '689', 'employee_name': 'Surender Verma'}, {'employee_id': '690', 'employee_name': 'Pramod Kumar Verma'}, {'employee_id': '691', 'employee_name': 'Pawan Kumar Verma'}, 
    {'employee_id': '692', 'employee_name': 'Ajay Verma'}, {'employee_id': '693', 'employee_name': 'Ravindra Verma'}, {'employee_id': '694', 'employee_name': 'Yogesh Verma'}, {'employee_id': '695', 'employee_name': 'Ankit Verma'}, {'employee_id': '696', 'employee_name': 'Anurag Verma'}, {'employee_id': '697', 'employee_name': 'Raju Verma'}, {'employee_id': '698', 'employee_name': 'Ankit Kumar Verma'}, {'employee_id': '699', 'employee_name': 'Santosh Kumar Verma'}, {'employee_id': '700', 'employee_name': 'Ashutosh Verma'}, {'employee_id': '701', 'employee_name': 'Rahul Verma'}, {'employee_id': '702', 'employee_name': 'Arjun Singh Verma'}, {'employee_id': '703', 'employee_name': 'Satish Kumar Verma'}, {'employee_id': '704', 'employee_name': 'Ajit Verma'}, {'employee_id': '705', 'employee_name': 'Vijay Verma'}, {'employee_id': '706', 'employee_name': 'Rajneesh Verma'}, {'employee_id': '707', 'employee_name': 'Praveen Verma'}, {'employee_id': '708', 'employee_name': 'Deepak Verma'}, {'employee_id': '709', 'employee_name': 'Rajesh Verma'}, {'employee_id': '710', 'employee_name': 'Sachin Kumar Verma'}, {'employee_id': '711', 'employee_name': 'Vijay Kumar Verma'}, 
    {'employee_id': '712', 'employee_name': 'Sanjay Verma'}, {'employee_id': '713', 'employee_name': 'Ravi Verma'}, {'employee_id': '714', 'employee_name': 'Anil Kumar Verma'}, {'employee_id': '715', 'employee_name': 'Sarvesh Kumar Verma'}, {'employee_id': '716', 'employee_name': 'Raj Kumar Verma'}, {'employee_id': '717', 'employee_name': 'Pankaj Verma'}, {'employee_id': '718', 'employee_name': 'Arun Kumar Verma'}, {'employee_id': '719', 'employee_name': 'Nitin Verma'}, {'employee_id': '720', 'employee_name': 'Rakesh Verma'}, {'employee_id': '721', 'employee_name': 'Sanjeev Kumar Verma'}, {'employee_id': '722', 'employee_name': 'Avinash Kumar Verma'}, {'employee_id': '723', 'employee_name': 'Manoj Kumar Verma'}, {'employee_id': '724', 'employee_name': 'Ashok Kumar Verma'}, {'employee_id': '725', 'employee_name': 'Amar Kumar Verma'}, {'employee_id': '726', 'employee_name': 'Vikas Verma'}, {'employee_id': '727', 'employee_name': 'Vinod Kumar Verma'}, {'employee_id': '728', 'employee_name': 'Gaurav Verma'}, {'employee_id': '729', 'employee_name': 'Vivek Verma'}, 
    {'employee_id': '730', 'employee_name': 'Anuj Kumar Verma'}, {'employee_id': '731', 'employee_name': 'Rajeev Verma'}, {'employee_id': '732', 'employee_name': 'Narendra Kumar Verma'}, {'employee_id': '733', 'employee_name': 'Pradeep Verma'}, {'employee_id': '734', 'employee_name': 'Sanjay Verma'}, {'employee_id': '735', 'employee_name': 'Naresh Kumar Gupta'}, {'employee_id': '736', 'employee_name': 'Raj Kumar Singh'}, {'employee_id': '737', 'employee_name': 'Om Prakash Verma'}, {'employee_id': '738', 'employee_name': 'Anuj Kumar Gupta'}, {'employee_id': '739', 'employee_name': 'Mohan Lal Sharma'}, {'employee_id': '740', 'employee_name': 'Rajesh Kumar Verma'}, {'employee_id': '741', 'employee_name': 'Mahesh Kumar Singh'}, {'employee_id': '742', 'employee_name': 'Devendra Kumar Gupta'}, {'employee_id': '743', 'employee_name': 'Rajan Sharma'}, {'employee_id': '744', 'employee_name': 'Rajiv Kumar Verma'}, {'employee_id': '745', 'employee_name': 'Rohit Kumar Gupta'}, {'employee_id': '746', 'employee_name': 'Ashish Kumar Singh'}, {'employee_id': '747', 'employee_name': 'Satish Kumar Verma'}, {'employee_id': '748', 'employee_name': 'Ajay Singh Gupta'}, {'employee_id': '749', 'employee_name': 'Manish Kumar Sharma'}, {'employee_id': '750', 'employee_name': 'Ankit Kumar Verma'}, 
    {'employee_id': '751', 'employee_name': 'Vijay Kumar Gupta'}, {'employee_id': '752', 'employee_name': 'Shiv Kumar Singh'}, {'employee_id': '753', 'employee_name': 'Anil Kumar Verma'}, {'employee_id': '754', 'employee_name': 'Surendra Kumar Gupta'}, {'employee_id': '755', 'employee_name': 'Amar Kumar Singh'}, {'employee_id': '756', 'employee_name': 'Vinay Kumar Verma'}, {'employee_id': '757', 'employee_name': 'Pradeep Kumar Gupta'}, {'employee_id': '758', 'employee_name': 'Pankaj Kumar Singh'}, {'employee_id': '759', 'employee_name': 'Dinesh Kumar Verma'}, {'employee_id': '760', 'employee_name': 'Arvind Kumar Gupta'}, {'employee_id': '761', 'employee_name': 'Harish Kumar Sharma'}, {'employee_id': '762', 'employee_name': 'Kamal Kumar Verma'}, {'employee_id': '763', 'employee_name': 'Vishal Verma Gupta'}, {'employee_id': '764', 'employee_name': 'Manish Singh Sharma'}, {'employee_id': '765', 'employee_name': 'Suresh Gupta Kumar'}, {'employee_id': '766', 'employee_name': 'Rajesh Sharma Singh'}, {'employee_id': '767', 'employee_name': 'Prakash Verma Gupta'}, {'employee_id': '768', 'employee_name': 'Ajay Sharma Singh'}, {'employee_id': '769', 'employee_name': 'Vijay Gupta Kumar'}, {'employee_id': '770', 'employee_name': 'Ramesh Singh Verma'}, {'employee_id': '771', 'employee_name': 'Rajendra Verma Gupta'}, 
    {'employee_id': '772', 'employee_name': 'Sunil Sharma Kumar'}, {'employee_id': '773', 'employee_name': 'Pradeep Verma Singh'}, {'employee_id': '774', 'employee_name': 'Mukesh Gupta Sharma'}, {'employee_id': '775', 'employee_name': 'Ashok Singh Verma'}, {'employee_id': '776', 'employee_name': 'Satish Verma Kumar'}, {'employee_id': '777', 'employee_name': 'Raju Sharma Gupta'}, {'employee_id': '778', 'employee_name': 'Shyam Gupta Singh'}, {'employee_id': '779', 'employee_name': 'Vinod Singh Verma'}, {'employee_id': '780', 'employee_name': 'Arjun Verma Sharma'}, {'employee_id': '781', 'employee_name': 'Naveen Kumar Gupta'}, {'employee_id': '782', 'employee_name': 'Manoj Verma Singh'}, {'employee_id': '783', 'employee_name': 'Santosh Gupta Verma'}, {'employee_id': '784', 'employee_name': 'Vikas Singh Sharma'}, {'employee_id': '785', 'employee_name': 'Deepak Verma Gupta'}, {'employee_id': '786', 'employee_name': 'Praveen Sharma Singh'}, {'employee_id': '787', 'employee_name': 'Ravi Singh Verma'}, {'employee_id': '788', 'employee_name': 'Pawan Verma Sharma'}, {'employee_id': '789', 'employee_name': 'Amit Kumar Gupta Singh'}, {'employee_id': '790', 'employee_name': 'Sanjay Verma Sharma'}, {'employee_id': '791', 'employee_name': 'Naresh Kumar Gupta Singh'}, {'employee_id': '792', 'employee_name': 'Raj Kumar Singh Verma'}, {'employee_id': '793', 'employee_name': 'Om Prakash Verma Sharma'}, {'employee_id': '794', 'employee_name': 'Anuj Kumar Gupta Singh'}, {'employee_id': '795', 'employee_name': 'Mohan Lal Sharma Verma'}, {'employee_id': '796', 'employee_name': 'Rajesh Kumar Verma Gupta'}, {'employee_id': '797', 'employee_name': 'Mahesh Kumar Singh Sharma'}, {'employee_id': '798', 'employee_name': 'Devendra Kumar Gupta Singh'}, {'employee_id': '799', 'employee_name': 'Rajan Sharma Verma'}, 
    {'employee_id': '800', 'employee_name': 'Rajiv Kumar Verma Gupta'}, {'employee_id': '801', 'employee_name': 'Rohit Kumar Gupta Singh'}, {'employee_id': '802', 'employee_name': 'Ashish Kumar Singh Verma'}, {'employee_id': '803', 'employee_name': 'Satish Kumar Verma Gupta'}, {'employee_id': '804', 'employee_name': 'Ajay Singh Gupta Singh'}, {'employee_id': '805', 'employee_name': 'Manish Kumar Sharma Verma'}, {'employee_id': '806', 'employee_name': 'Ankit Kumar Verma Gupta'}, {'employee_id': '807', 'employee_name': 'Vijay Kumar Gupta Singh'}, {'employee_id': '808', 'employee_name': 'Shiv Kumar Singh Verma'}, {'employee_id': '809', 'employee_name': 'Anil Kumar Verma Gupta'}, {'employee_id': '810', 'employee_name': 'Surendra Kumar Gupta Singh'}, {'employee_id': '811', 'employee_name': 'Amar Kumar Singh Verma'}, {'employee_id': '812', 'employee_name': 'Vinay Kumar Verma Gupta'}, {'employee_id': '813', 'employee_name': 'Pradeep Kumar Gupta Singh'}, {'employee_id': '814', 'employee_name': 'Pankaj Kumar Singh Verma'}, {'employee_id': '815', 'employee_name': 'Dinesh Kumar Verma Gupta'}, {'employee_id': '816', 'employee_name': 'Arvind Kumar Gupta Singh'}, {'employee_id': '817', 'employee_name': 'Harish Kumar Sharma Verma'}, {'employee_id': '818', 'employee_name': 'Kamal Kumar Verma Gupta'}, {'employee_id': '819', 'employee_name': 'Vishal Verma Gupta Singh'}, {'employee_id': '820', 'employee_name': 'Manish Singh Sharma Verma'}, 
    {'employee_id': '821', 'employee_name': 'Suresh Gupta Kumar Verma'}, {'employee_id': '822', 'employee_name': 'Rajesh Sharma Singh Verma'}, {'employee_id': '823', 'employee_name': 'Prakash Singh Verma Gupta'}, {'employee_id': '824', 'employee_name': 'Ajay Verma Gupta Singh'}, {'employee_id': '825', 'employee_name': 'Vijay Sharma Kumar Verma'}, {'employee_id': '826', 'employee_name': 'Ramesh Gupta Singh Verma'}, {'employee_id': '827', 'employee_name': 'Rajendra Kumar Verma Singh'}, {'employee_id': '828', 'employee_name': 'Sunil Verma Gupta Sharma'}, {'employee_id': '829', 'employee_name': 'Pradeep Sharma Kumar Verma'}, {'employee_id': '830', 'employee_name': 'Mukesh Singh Gupta Verma'}, {'employee_id': '831', 'employee_name': 'Ashok Verma Sharma Singh'}, {'employee_id': '832', 'employee_name': 'Satish Sharma Gupta Kumar'}, {'employee_id': '833', 'employee_name': 'Raju Gupta Verma Singh'}, {'employee_id': '834', 'employee_name': 'Shyam Singh Verma Gupta'}, {'employee_id': '835', 'employee_name': 'Vinod Gupta Sharma Kumar'}, {'employee_id': '836', 'employee_name': 'Arjun Verma Singh Sharma'}, {'employee_id': '837', 'employee_name': 'Naveen Gupta Kumar Verma'}, {'employee_id': '838', 'employee_name': 'Manoj Sharma Gupta Singh'}, {'employee_id': '839', 'employee_name': 'Santosh Singh Verma Sharma'}, {'employee_id': '840', 'employee_name': 'Vikas Verma Gupta Singh'}, {'employee_id': '841', 'employee_name': 'Deepak Sharma Kumar Verma'}, {'employee_id': '842', 'employee_name': 'Praveen Gupta Singh Sharma'}, {'employee_id': '843', 'employee_name': 'Ravi Gupta Verma Singh'}, {'employee_id': '844', 'employee_name': 'Pawan Verma Sharma Gupta'}, {'employee_id': '845', 'employee_name': 'Amit Verma Sharma Kumar'}, {'employee_id': '846', 'employee_name': 'Sanjay Sharma Gupta Singh'}, {'employee_id': '847', 'employee_name': 'Naresh Gupta Singh Verma'}, {'employee_id': '848', 'employee_name': 'Raj Kumar Verma Sharma'}, {'employee_id': '849', 'employee_name': 'Om Prakash Sharma Verma'}, 
    {'employee_id': '850', 'employee_name': 'Anuj Gupta Singh Verma'}, {'employee_id': '851', 'employee_name': 'Mohan Lal Verma Sharma'}, {'employee_id': '852', 'employee_name': 'Rajesh Verma Gupta Singh'}, {'employee_id': '853', 'employee_name': 'Mahesh Singh Verma Sharma'}, {'employee_id': '854', 'employee_name': 'Devendra Gupta Singh Verma'}, {'employee_id': '855', 'employee_name': 'Rajan Verma Sharma Singh'}, {'employee_id': '856', 'employee_name': 'Rajiv Verma Gupta Sharma'}, {'employee_id': '857', 'employee_name': 'Rohit Verma Singh Gupta'}, {'employee_id': '858', 'employee_name': 'Ashish Singh Verma Sharma'}, {'employee_id': '859', 'employee_name': 'Satish Verma Gupta Singh'}, {'employee_id': '860', 'employee_name': 'Ajay Gupta Singh Verma'}, {'employee_id': '861', 'employee_name': 'Manish Verma Sharma Gupta'}, {'employee_id': '862', 'employee_name': 'Vijay Gupta Singh Sharma'}, {'employee_id': '863', 'employee_name': 'Shiv Gupta Verma Singh'}, {'employee_id': '864', 'employee_name': 'Anil Gupta Verma Sharma'}, {'employee_id': '865', 'employee_name': 'Surendra Gupta Singh Verma'}, {'employee_id': '866', 'employee_name': 'Amar Gupta Singh Verma'}, {'employee_id': '867', 'employee_name': 'Vinay Gupta Verma Sharma'}, {'employee_id': '868', 'employee_name': 'Pradeep Gupta Singh Verma'}, {'employee_id': '869', 'employee_name': 'Pankaj Gupta Singh Verma'}, {'employee_id': '870', 'employee_name': 'Dinesh Gupta Verma Sharma'}, {'employee_id': '871', 'employee_name': 'Arvind Gupta Singh Verma'}, {'employee_id': '872', 'employee_name': 'Harish Gupta Sharma Verma'}, {'employee_id': '873', 'employee_name': 'Kamal Gupta Verma Singh'}, {'employee_id': '874', 'employee_name': 'Vishal Gupta Singh Verma'}, {'employee_id': '875', 'employee_name': 'Manish Gupta Verma Sharma'}, {'employee_id': '876', 'employee_name': 'Suresh Gupta Verma Singh'}, {'employee_id': '877', 'employee_name': 'Rajesh Gupta Sharma Verma'}, {'employee_id': '878', 'employee_name': 'Prakash Sharma Verma Gupta'}, {'employee_id': '879', 'employee_name': 'Ajay Verma Singh Gupta'}, 
    {'employee_id': '880', 'employee_name': 'Vijay Sharma Verma Gupta'}, {'employee_id': '881', 'employee_name': 'Ramesh Kumar Singh Verma'}, {'employee_id': '882', 'employee_name': 'Rajendra Singh Verma Gupta'}, {'employee_id': '883', 'employee_name': 'Sunil Kumar Gupta Singh'}, {'employee_id': '884', 'employee_name': 'Pradeep Kumar Verma Gupta'}, {'employee_id': '885', 'employee_name': 'Mukesh Kumar Sharma Singh'}, {'employee_id': '886', 'employee_name': 'Ashok Kumar Sharma Verma'}, {'employee_id': '887', 'employee_name': 'Satish Kumar Verma Gupta'}, {'employee_id': '888', 'employee_name': 'Raju Kumar Gupta Verma'}, {'employee_id': '889', 'employee_name': 'Shyam Kumar Singh Gupta'}, {'employee_id': '890', 'employee_name': 'Vinod Kumar Verma Sharma'}, {'employee_id': '891', 'employee_name': 'Arjun Kumar Gupta Singh'}, {'employee_id': '892', 'employee_name': 'Naveen Kumar Sharma Verma'}, {'employee_id': '893', 'employee_name': 'Manoj Kumar Singh Gupta'}, {'employee_id': '894', 'employee_name': 'Santosh Kumar Verma Sharma'}, {'employee_id': '895', 'employee_name': 'Vikas Kumar Gupta Singh'}, {'employee_id': '896', 'employee_name': 'Deepak Kumar Verma Sharma'}, {'employee_id': '897', 'employee_name': 'Praveen Kumar Gupta Sharma'}, {'employee_id': '898', 'employee_name': 'Ravi Kumar Verma Singh'}, {'employee_id': '899', 'employee_name': 'Pawan Kumar Singh Verma'}, {'employee_id': '900', 'employee_name': 'Amit Kumar Verma Sharma'}, {'employee_id': '901', 'employee_name': 'Sanjay Kumar Sharma Gupta'}, {'employee_id': '902', 'employee_name': 'Naresh Kumar Gupta Singh'}, {'employee_id': '903', 'employee_name': 'Raj Kumar Verma Sharma'}, {'employee_id': '904', 'employee_name': 'Om Kumar Sharma Verma'}, {'employee_id': '905', 'employee_name': 'Anuj Kumar Gupta Singh'}, {'employee_id': '906', 'employee_name': 'Mohan Kumar Verma Sharma'}, {'employee_id': '907', 'employee_name': 'Rajesh Kumar Verma Gupta'}, {'employee_id': '908', 'employee_name': 'Mahesh Kumar Singh Verma'}, {'employee_id': '909', 'employee_name': 'Devendra Kumar Gupta Singh'}, 
    {'employee_id': '910', 'employee_name': 'Rajan Kumar Verma Sharma'}, {'employee_id': '911', 'employee_name': 'Rajiv Kumar Verma Gupta'}, {'employee_id': '912', 'employee_name': 'Rohit Kumar Verma Singh'}, {'employee_id': '913', 'employee_name': 'Ashish Kumar Singh Verma'}, {'employee_id': '914', 'employee_name': 'Satish Kumar Verma Gupta'}, {'employee_id': '915', 'employee_name': 'Ajay Kumar Gupta Singh'}, {'employee_id': '916', 'employee_name': 'Manish Kumar Verma Sharma'}, {'employee_id': '917', 'employee_name': 'Vijay Kumar Gupta Sharma'}, {'employee_id': '918', 'employee_name': 'Shiv Kumar Gupta Verma'}, {'employee_id': '919', 'employee_name': 'Anil Kumar Gupta Verma'}, {'employee_id': '920', 'employee_name': 'Surendra Kumar Gupta Singh'},
    {'employee_id': '921', 'employee_name': 'Shivani'},{'employee_id': '1', 'employee_name': 'Olivia'}, {'employee_id': '2', 'employee_name': 'Emma'}, {'employee_id': '3', 'employee_name': 'Ava'}, {'employee_id': '4', 'employee_name': 'Charlotte'}, {'employee_id': '5', 'employee_name': 'Sophia'},
    {'employee_id': '6', 'employee_name': 'Amelia'}, {'employee_id': '7', 'employee_name': 'Isabella'}, {'employee_id': '8', 'employee_name': 'Mia'}, 
    {'employee_id': '9', 'employee_name': 'Evelyn'}, {'employee_id': '10', 'employee_name': 'Harper'}, {'employee_id': '11', 'employee_name': 'Camila'}, {'employee_id': '12', 'employee_name': 'Gianna'},
    
    ]


# Tokenize the dataset
tokenizer = GPT2Tokenizer.from_pretrained('/home/tejavathsaikumar/models/gpt2-xl')
tokenizer.pad_token = tokenizer.eos_token
tokenized_data = [
    {
        'input_ids': tokenizer.encode(item['employee_id'], add_special_tokens=False),
        'target_ids': tokenizer.encode(item['employee_name'], add_special_tokens=False)
    }
    for item in data
]

# Define your dataset and dataloader
max_length = 64  # Set a maximum sequence length
dataset = EmployeeDataset(tokenized_data, max_length=max_length)

def collate_fn(batch):
    inputs, targets = zip(*batch)

    # Filter out empty sequences
    inputs = [seq for seq in inputs if len(seq) > 0]
    targets = [seq for seq in targets if len(seq) > 0]

    # Determine the maximum sequence length in the batch
    max_length = max(len(seq) for seq in inputs + targets)

    # Pad the inputs and targets to the maximum length
    inputs = pad_sequence([torch.tensor(seq + [tokenizer.pad_token_id] * (max_length - len(seq))) for seq in inputs], batch_first=True)
    targets = pad_sequence([torch.tensor(seq + [tokenizer.pad_token_id] * (max_length - len(seq))) for seq in targets], batch_first=True)

    # Create attention masks
    attention_mask = (inputs != tokenizer.pad_token_id).float()

    return inputs, attention_mask, targets

dataloader = DataLoader(dataset, batch_size=3, shuffle=True, collate_fn=collate_fn)

# Load the GPT-2 model
model = GPT2LMHeadModel.from_pretrained('/home/tejavathsaikumar/models/gpt2-xl')
config = GPT2Config.from_pretrained('/home/tejavathsaikumar/models/gpt2-xl')
model.resize_token_embeddings(len(tokenizer))

# Fine-tune the model
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.train()

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-6)
criterion = torch.nn.CrossEntropyLoss()

num_epochs = 2
for epoch in range(num_epochs):
    for inputs, attention_mask, targets in dataloader:
        inputs = inputs.to(device)
        attention_mask = attention_mask.to(device)
        targets = targets.to(device)

        outputs = model(inputs, attention_mask=attention_mask, labels=targets)
        loss = outputs.loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

# Inference (generate employee name for a given employee ID)
employee = "what is  the employee_name for the person whose employee_id is 454 ?"  
input_ids = tokenizer.encode(employee, add_special_tokens=False, return_tensors="pt").to(device)

model.eval()
with torch.no_grad():
    output_ids = model.generate(
        input_ids,
        attention_mask=input_ids.ne(tokenizer.pad_token_id),
        max_length=100,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.7
    )
    output_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    print("Employee Name:", output_text)
